### ISSUE TITLE
[ERROR]: This import is never used as a value and must use 'import type'

### ISSUE THREAD

**Issue by hu-qi** [justjavac/zhihu-trending-top-search#2]
可能需要在**import** 类型的时候添加**type**关键字。
本地运行
```
deno run --unstable --allow-net --allow-read --allow-write --importmap=import_map.json mod.ts
```

报错：
```log
error: TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { SearchWord } from "./types.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/gpdi/Documents/huqi/deno/jjc/zhihu-trending-top-search/utils.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { SearchWord, TopSearch } from "./types.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/gpdi/Documents/huqi/deno/jjc/zhihu-trending-top-search/mod.ts:7:1
```

![](https://gitee.com/hu-qi/cdn/raw/master/2020-11-28/1606557160179-image.png)

**Comment by hu-qi** [comment]
可能又是版本的问题

**Comment by hu-qi** [comment]
找着了：https://deno.land/posts/v1.5#stricter-type-checks-in-stable

我厚着脸皮刷个pr
